// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Page$ReactTemplate = require("./Page.bs.js");

((require('./main.js')));

ReactDOMRe.renderToElementWithId(ReasonReact.element(undefined, undefined, Page$ReactTemplate.make(/* array */[])), "build");

/*  Not a pure module */
