// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var MainHeader$ReactTemplate = require("./MainHeader.bs.js");
var MainSidebar$ReactTemplate = require("./MainSidebar.bs.js");

((require('./main.js')));

ReactDOMRe.renderToElementWithId(ReasonReact.element(undefined, undefined, MainHeader$ReactTemplate.make("ALDEYVT", "AdminLTE", /* array */[])), "header");

ReactDOMRe.renderToElementWithId(ReasonReact.element(undefined, undefined, MainSidebar$ReactTemplate.make("Deyvison Guilherme", "Ativo", /* array */[])), "sidebar");

/*  Not a pure module */
