// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Box$ReactTemplate = require("./Box.bs.js");
var Button$ReactTemplate = require("./Button.bs.js");
var MainHeader$ReactTemplate = require("./MainHeader.bs.js");
var MainSidebar$ReactTemplate = require("./MainSidebar.bs.js");
var ContentWrapper$ReactTemplate = require("./ContentWrapper.bs.js");

var component = ReasonReact.statelessComponent("Page");

function make(param) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (_self) {
              return React.createElement("div", undefined, ReasonReact.element(undefined, undefined, MainHeader$ReactTemplate.make("LetMeGo", /* array */[])), ReasonReact.element(undefined, undefined, MainSidebar$ReactTemplate.make(/* array */[])), ReasonReact.element(undefined, undefined, ContentWrapper$ReactTemplate.make(/* array */[ReasonReact.element(undefined, undefined, Box$ReactTemplate.Row[/* make */1](/* array */[ReasonReact.element(undefined, undefined, Box$ReactTemplate.Col[/* make */1](8, /* array */[
                                                      ReasonReact.element(undefined, undefined, Box$ReactTemplate.Primary[/* make */1](/* array */[ReasonReact.element(undefined, undefined, Box$ReactTemplate.Header[/* make */1](/* array */[ReasonReact.element(undefined, undefined, Box$ReactTemplate.Title[/* make */1]("Cadastro de clientes", /* array */[]))]))])),
                                                      ReasonReact.element(undefined, undefined, Box$ReactTemplate.Body[/* make */1](/* array */[ReasonReact.element(undefined, undefined, Button$ReactTemplate.make("btn-primary", "btn-xs", "Clique aqui", /* array */[]))])),
                                                      ReasonReact.element(undefined, undefined, Box$ReactTemplate.Footer[/* make */1](/* array */[]))
                                                    ]))]))])));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* jsElementWrapped */component[/* jsElementWrapped */13]
        ];
}

exports.component = component;
exports.make = make;
/* component Not a pure module */
